dataset: "LJSpeech"

path:
  corpus_path: "/mnt/nfs2/speech-datasets/en/LJSpeech-1.1"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LJSpeech"
  preprocessed_path: "./preprocessed_data/LJSpeech"
  train_filelist: "filelists/train.txt"
  val_filelist: "filelists/val.txt"
preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 44100
    max_wav_value: 32768.0
  stft:
    filter_length: 2048
    hop_length: 512
    win_length: 2048
  mel:
    n_mel_channels: 128
    mel_fmin: 40
    mel_fmax: 16000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    pitch_type: "cwt" # support 'frame', 'ph', 'cwt'
    pitch_norm: "log" # support 'standard', 'log'
    pitch_norm_eps: 0.000000001
    pitch_ar: False
    with_f0: True
    with_f0cwt: True
    use_uv: True
    f0_mean: 214.31683793057
    f0_std: 63.97520977575229
    cwt_scales: -1
  energy:
    feature: "frame_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
