# sampling_rate: 44100
# mel_channels: 128
# hidden_size: 256

type: DiffSVC
_target_: fish_diffusion.modules.diffusion.DiffusionSVC
diffusion:
  type: GaussianDiffusion
  mel_channels: ${mel_channels:}
  noise_schedule: linear
  timesteps: 1000
  max_beta: 0.01
  s: 0.008
  noise_loss: smoothed-l1
  denoiser:
    type: WaveNetDenoiser
    mel_channels: ${mel_channels:}
    d_encoder: ${hidden_size:}
    residual_channels: 512
    residual_layers: 20
    dilation_cycle: 4
    use_linear_bias: true
  sampler_interval: 10
  spec_min:
    - -5
  spec_max:
    - 0
text_encoder:
  type: NaiveProjectionEncoder
  input_size: 256
  output_size: ${hidden_size:}
speaker_encoder:
  type: NaiveProjectionEncoder
  input_size: 10
  output_size: ${hidden_size:}
  use_embedding: true
pitch_encoder:
  type: NaiveProjectionEncoder
  input_size: 1
  output_size: ${hidden_size:}
  use_embedding: false
  preprocessing: ${pitch_to_scale:}
vocoder:
  _target_: fish_diffusion.modules.vocoders.nsf_hifigan.nsf_hifigan.NsfHifiGAN
  type: NsfHifiGAN
  checkpoint_path: checkpoints/nsf_hifigan/model
  sampling_rate: ${sampling_rate:}
  mel_channels: ${mel_channels:}
  use_natural_log: false
