type: HiFiSVC
hidden_size: ${hidden_size:}
text_encoder:
  _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
  input_size: 256 
  output_size: ${hidden_size:}
speaker_encoder:
  _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
  input_size: ${speaker_embedding_size:}
  output_size: ${hidden_size:}
  use_embedding: true
pitch_encoder:
  _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
  input_size: 1
  output_size: ${hidden_size:}
  use_embedding: false
  preprocessing:
    _target_: fish_diffusion.utils.pitch.pitch_to_scale 
pitch_shift_encoder:
  _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
  input_size: 1
  output_size: ${hidden_size:}
  use_embedding: false
energy_encoder:
  _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
  input_size: 1
  output_size: ${hidden_size:}
  use_embedding: false
encoder:
  _target_: fish_diffusion.modules.HiFiGAN
  sampling_rate: ${sampling_rate:}
      # Model config
  resblock: 1
  upsample_rates: [8, 8, 2, 2, 2]
  upsample_kernel_sizes: [16, 16, 8, 2, 2]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  discriminator_periods: [3, 5, 7, 11, 17, 23, 37]
  # The folowing parameters are used for validation
  num_mels: 256
  n_fft: 2048
  hop_size: 512
  win_size: 2048
  fmin: 40
  fmax: 16000
  # The following parameters are used for training
  multi_scale_mels: 
    - [2048, 512, 2048] # (n_fft, hop_size, win_size)
    - [2048, 270, 1080]
    - [4096, 540, 2160]
  multi_scale_stfts: 
    - [512, 50, 240]  # (n_fft, hop_size, win_size)
    - [1024, 120, 600]
    - [2048, 240, 1200]