text_features_extractor_type: HubertSoft
pitch_extractor_type: ParselMouthPitchExtractor
pretrained: null
resume: null
tensorboard: false
resume_id: null
entity: null
name: null
only_train_speaker_embeddings: false
path: dataset
clean: false
num_workers: 8
no_augmentation: true
model:
  type: HiFiSVC
  hidden_size: 256
  text_encoder:
    _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
    input_size: 256
    output_size: 256
  speaker_encoder:
    _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
    input_size: 1
    output_size: 256
    use_embedding: true
  pitch_encoder:
    _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
    input_size: 1
    output_size: 256
    use_embedding: false
    preprocessing:
      _target_: fish_diffusion.utils.pitch.pitch_to_scale
  pitch_shift_encoder:
    _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
    input_size: 1
    output_size: 256
    use_embedding: false
  energy_encoder:
    _target_: fish_diffusion.modules.encoders.naive_projection.NaiveProjectionEncoder
    input_size: 1
    output_size: 256
    use_embedding: false
  encoder:
    _target_: fish_diffusion.modules.HiFiGAN
    sampling_rate: 44100
    resblock: 1
    upsample_rates:
    - 8
    - 8
    - 2
    - 2
    - 2
    upsample_kernel_sizes:
    - 16
    - 16
    - 8
    - 2
    - 2
    upsample_initial_channel: 512
    resblock_kernel_sizes:
    - 3
    - 7
    - 11
    resblock_dilation_sizes:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    discriminator_periods:
    - 3
    - 5
    - 7
    - 11
    - 17
    - 23
    - 37
    num_mels: 256
    n_fft: 2048
    hop_size: 512
    win_size: 2048
    fmin: 40
    fmax: 16000
    multi_scale_mels:
    - - 2048
      - 512
      - 2048
    - - 2048
      - 270
      - 1080
    - - 4096
      - 540
      - 2160
    multi_scale_stfts:
    - - 512
      - 50
      - 240
    - - 1024
      - 120
      - 600
    - - 2048
      - 240
      - 1200
preprocessing:
  text_features_extractor:
    _target_: fish_diffusion.modules.feature_extractors.content_vec.ContentVec
  pitch_extractor:
    _target_: fish_diffusion.modules.pitch_extractors.parsel_mouth.ParselMouthPitchExtractor
    keep_zeros: false
    f0_min: 40.0
    f0_max: 1600.0
  energy_extractor:
    _target_: fish_diffusion.modules.energy_extractors.rms.RMSEnergyExtractor
  augmentations:
  - type: FixedPitchShifting
    key_shifts:
    - -5.0
    - 5.0
    probability: 0.75,
model_type: HiFiSVC
dataset:
  train:
    _target_: fish_diffusion.datasets.concat.ConcatDataset
    datasets:
    - _target_: fish_diffusion.datasets.hifisinger.HiFiSVCDataset
      path: dataset/train/opencpop
      segment_size: 16384
      speaker_id: 0
    collate_fn: fish_diffusion.datasets.hifisinger.HiFiSVCDataset.collate_fn
  valid:
    _target_: fish_diffusion.datasets.concat.ConcatDataset
    datasets:
    - _target_: fish_diffusion.datasets.hifisinger.HiFiSVCDataset
      path: dataset/valid
    collate_fn: fish_diffusion.datasets.hifisinger.HiFiSVCDataset.collate_fn
dataloader:
  train:
    batch_size: 20
    shuffle: true
    num_workers: 2
    persistent_workers: true
  valid:
    batch_size: 2
    shuffle: false
    num_workers: 2
    persistent_workers: true
scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0002
  betas:
  - 0.8
  - 0.99
  eps: 1.0e-09
trainer:
  accelerator: gpu
  devices: -1
  gradient_clip_val: null
  log_every_n_steps: 10
  val_check_interval: 5000
  check_val_every_n_epoch: null
  max_steps: 1000000.0
  precision: 16
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    filename: '{epoch}-{step}-{valid_loss:.2f}'
    every_n_train_steps: 10000
    save_top_k: -1
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
  strategy: 
    _target_: pytorch_lightning.strategies.DDPStrategy 
    find_unused_parameters: true
    process_group_backend: nccl
    gradient_as_bucket_view: true
    ddp_comm_hook: torch.distributed.algorithms.ddp_comm_hooks.default_hooks.fp16_compress_hook
